title: HandJoy Wiki
description: HandJoy Wiki build by LONG HAUL's theme

url: https://handjoy.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: handjoy
   # twitter: brianmaierjr
   # facebook: brianmaierjr
   email: handjoy@163.com

google_analytics: "UA-58263416-1"

